Update file for currency converting
prebid/currency-file-generator pull request #21
Opened 2021-04-06 18:08 UTC by snahornyi

2021-04-07 07:35 UTC, rpanchyk requested changes

2021-04-07 07:35 UTC, rpanchyk commented on src/currencyRatesFileGen.js
> +function makeid(length) {
Please rename to `getRandomString`.

2021-04-07 07:35 UTC, rpanchyk commented on src/currencyRatesFileGen.js
> +    const randomPrefix = makeid(7);
Please add a comment why we need this random prefix.

2021-04-07 07:35 UTC, rpanchyk commented on src/currencyRatesFileGen.js
> +    rate["EUR"] = 1/ currencyObject.rate;
Pls add comment here why we need to add separate currency. Or even more, extract missing currencies to array and process them here. Up to you.

2021-04-07 08:34 UTC, rpanchyk approved these changes

2021-04-08 13:54 UTC, patmmccann commented
This appears to publish the date it ran instead of the date in the ecb file. If ecb were to stop updating their file but continue publishing the xml, what check do we have?

2021-04-08 13:56 UTC, patmmccann requested changes
Can you change dataAsOf to pull the date from the source file?

2021-04-22 21:12 UTC, bretg commented
@patmmccann - looks like your comment was incorporated - please re-review

2021-04-23 00:42 UTC, patmmccann commented
Yes much appreciated, lgtm

2021-05-03 16:37 UTC, merged